### ISSUE TITLE
Similar Saliency map regardless of prompt

### ISSUE THREAD

**Issue by dsouzinator** [HealthX-Lab/MedCLIP-SAM#3]
I've been experimenting with the colab notebook, and I found that biomedclip with VIT-B/16 and gScoreCAM produces similar saliency maps regardless of the text prompt. I've added some sample images and text below. Any insights into what may be causing this? The model seems to consistently select the tumor region, producing high false positive rates with respect to the prompt.

![Unknown](https://github.com/user-attachments/assets/87fe158a-11f2-4a50-aab9-3388262daf75)   
Prompt: "an image of a brain tumor"

![Unknown-3](https://github.com/user-attachments/assets/24119054-2617-4587-9583-13ae94e7c76f)   
Prompt: "sitting on a chair"

![Unknown-4](https://github.com/user-attachments/assets/615b0b30-890e-4bf8-96ab-17667dd66030)   
Prompt: "ljashdbflsabdf"

**Comment by TahaKoleilat** [comment]
Hi @dsouzinator,

Thank you for your interest in our work.

I think this could be due to the image example itself. The gScoreCAM method could sometimes be heavily biased towards certain features found in images regardless of the text prompt. Try testing different images to see whether the results are different. I would also suggest looking at our recent work where we used a different saliency map generation technique: https://github.com/HealthX-Lab/MedCLIP-SAMv2.

Let me know if you have any other questions.

**Comment by TahaKoleilat** [comment]
I will close this for now. Feel free to open in case you have any further questions.
